spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://192.168.214.1:3306/manager?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.214.1:3306/manager?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
mybatis-plus:
  type-aliases-package: com.linguxe.model.entity
  mapper-locations: classpath:mappers/*.xml
server:
  port: 9091
